name = "MotionCaptureJointCalibration"
uuid = "d0551c8d-3c54-58b6-a75a-e266c30cc699"
version = "0.3.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
JuMP = "~0.18.0"
NBInclude = "≥ 1.1.0"
Requires = "≥ 0.5.2"
RigidBodyDynamics = "≥ 0.6.0"
RigidBodyTreeInspector = "≥ 0.3.1"
julia = "≥ 0.7.0"

[extras]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DrakeVisualizer = "49c7015b-b8db-5bc5-841b-fcb31c578176"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RigidBodyTreeInspector = "82daab19-8fc9-5c1e-9f69-37d6aaa0269b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ValkyrieRobot = "c74b26e8-f247-5d24-b013-c11a2bbd97c6"

[targets]
test = ["Interact", "ForwardDiff", "Test", "Random", "LinearAlgebra", "Ipopt", "RigidBodyTreeInspector", "ColorTypes", "GeometryTypes", "NBInclude", "DrakeVisualizer", "Parameters", "ValkyrieRobot"]
